### ISSUE TITLE
Generate Changelog - Handle HTTPS remote origin URLs

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/release-tools#19]
In findRepoName, handle the following URL format: ``https://github.com/enonic/xp.git``

**Comment by sigdestad** [comment]
Do we support url-style repo names?

**Comment by sigdestad** [comment]
I thought repo and branch names were very restrictive?

**Comment by jsi** [comment]
@sigdestad : This is only for our internal tool to generate changlog entries.  I have always used the more secure format (git@github.com:enonic/xp.git), when I have generated changelogs for releases.

Yesterday, Glenn had a need to see what is in the changelog since v7.0.0 and used the simpler, less secure format to do so.  Since this is a very easy fix, maybe 10 minutes, I will implement this, later in the week, as well as imporove the documentation a little, so it will be easier for everybody who want to, to generate a changelog at will.

**Comment by jsi** [comment]
The error message that appears if https is used instead of ssh, is described in #20

**Comment by rymsha** [comment]
Fixed it when converted to Github Action
